version: '3'
# This Compose file is super convenient
# as we do not have to type all the parameters to pass to the docker run command.
# We can declaratively do that using a Compose file.

services:
 web:
  build:
   context: .
  container_name: web
  ports:
  - 5000:5000
  volumes:
  - ./:/app
  environment:
   MYSQL_HOST: mysql_app
   MYSQL_USER: root
   MYSQL_PWD: yuekang333
   MYSAL_DB: app_data
   LANG: zh_CN.UTF-8
   LC_CTYPE: zh_CN.UTF-8
   PYTHONIOENCODING: utf-8

 mysql_app:
  image: mysql
  ports:
  - 3306:3306
  container_name: mysql_app
  environment:
   MYSQL_ROOT_PASSWORD: yuekang333
   MYSQL_DATABASE: app_data
   TZ: Asia/Shanghai
  volumes:
   - "./data/mysql_data:/var/lib/mysql"
  command: [
     '--character-set-server=utf8mb4',
     '--collation-server=utf8mb4_general_ci',
     '--max_connections=3000'
  ]